spring.application.name=project1
spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/project1
spring.datasource.username=postgres
spring.datasource.password=postGree

jwt.secret=qwertyuiopasdfghjklzxcvbnm1234567890
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

cloudinary.cloud-name=swafuttr
cloudinary.api-key=752662631895831
cloudinary.api-secret=SK_wo8bjn_MJG18r-YqjkFpYwig